#!/usr/bin/env python

import sys, os

def add_gist(filename):
	return

if(len(sys.argv) == 2):
	add_gist(sys.argv[1])
else:
	print("Usage:\n")
	print("addgist gistfile.py\n")
	print("Please also note that you need to set up GitHub credentials in the script")