#!/usr/bin/env python

import sys, os
from pygithub3 import Github

#API credentials
github_user = "username"
github_password = "password"
is_public = True

github = Github(login=github_user, password=github_password)

def add_gist(filepath, description):
	if os.path.isfile(filepath) and len(description) > 0:

		fp = open(filepath, "r")
		content = fp.read()
		fp.close()

		if len(content) > 0:
			filename = os.path.basename(filepath)
			github.gists.create(dict(description=description, public=is_public, files={filename: {'content': content}}))
		else:
			print("File should not be empty!")
		
	else:
		print("Please check if " + filepath + " exists!")

if(len(sys.argv) == 3):
	add_gist(sys.argv[1], sys.argv[2])
else:
	print("Usage:\n")
	print("addgist gistfile.py 'gist description'\n")
	print("Please also note that you need to set up GitHub credentials in the script")